
import { useState } from "react";
import { Lightbulb, Check, ArrowRight, File } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "@/hooks/use-toast";
import OllieAvatar from "@/components/OllieAvatar";
import MainLayout from "@/layouts/MainLayout";

const Workspace = () => {
  const [content, setContent] = useState("");
  const [summary, setSummary] = useState("");
  const [showHint, setShowHint] = useState(false);
  
  const generateSummary = () => {
    if (content.trim().length < 50) {
      toast({
        title: "Not enough content",
        description: "Please enter at least 50 characters to generate a summary.",
        variant: "destructive",
      });
      return;
    }
    
    // In a real app, this would call an AI API
    const fakeSummary = `This is a summarized version of your content. In a real application, this would be generated by an AI model based on the text you've entered. The summary would highlight key points and main ideas from your original text.`;
    
    setSummary(fakeSummary);
  };
  
  const handleHintClick = () => {
    setShowHint(!showHint);
  };
  
  const saveContent = () => {
    toast({
      title: "Content saved!",
      description: "Your work has been saved successfully.",
    });
  };
  
  return (
    <MainLayout>
      <div className="max-w-4xl mx-auto">
        <div className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-2xl font-bold">Creative Workspace</h1>
            <p className="text-gray-600">Organize your thoughts and create summaries</p>
          </div>
          <OllieAvatar greeting="Need help with your writing? I'm here to assist!" />
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="bg-white rounded-xl shadow-md p-6">
            <h2 className="text-lg font-bold mb-4">Your Notes</h2>
            <div className="relative">
              <Textarea
                placeholder="Start typing your content here..."
                className="min-h-[300px] resize-none p-4"
                value={content}
                onChange={(e) => setContent(e.target.value)}
              />
              
              {content.length > 0 && content.length < 50 && (
                <div 
                  className="absolute bottom-4 right-4 bg-omni-mint/90 text-black rounded-lg px-3 py-1.5 shadow-sm cursor-pointer animate-fade-in flex items-center gap-2"
                  onClick={handleHintClick}
                >
                  <Lightbulb className="h-4 w-4" />
                  <span className="text-sm font-medium">Need a hint?</span>
                </div>
              )}
              
              {showHint && (
                <div className="absolute top-full mt-2 right-0 bg-white border border-gray-200 rounded-lg shadow-lg p-4 z-10 w-full md:w-2/3 animate-fade-in">
                  <div className="flex justify-between items-start">
                    <h3 className="font-medium text-sm">Writing Suggestions</h3>
                    <button 
                      onClick={() => setShowHint(false)}
                      className="text-gray-400 hover:text-gray-600"
                    >
                      ✕
                    </button>
                  </div>
                  <ul className="mt-2 text-sm text-gray-600 space-y-2">
                    <li className="flex items-start gap-2">
                      <Check className="h-4 w-4 text-green-500 mt-0.5" />
                      <span>Try writing at least 5-6 sentences about your topic</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <Check className="h-4 w-4 text-green-500 mt-0.5" />
                      <span>Include key facts or main ideas you want to remember</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <Check className="h-4 w-4 text-green-500 mt-0.5" />
                      <span>Write in your own words to better understand the content</span>
                    </li>
                  </ul>
                </div>
              )}
            </div>
            
            <div className="flex justify-between mt-4">
              <Button 
                variant="outline" 
                onClick={saveContent}
                className="flex items-center gap-2"
              >
                <File className="h-4 w-4" />
                Save
              </Button>
              
              <Button
                onClick={generateSummary}
                disabled={content.trim().length < 50}
                className="bg-omni-mint hover:bg-omni-mint/90 text-black flex items-center gap-2"
              >
                Create Summary
                <ArrowRight className="h-4 w-4" />
              </Button>
            </div>
          </div>
          
          <div className="bg-white rounded-xl shadow-md p-6">
            <h2 className="text-lg font-bold mb-4">AI-Generated Summary</h2>
            <div className="border border-gray-200 rounded-lg min-h-[300px] p-4 bg-gray-50">
              {summary ? (
                <div className="animate-fade-in">
                  <p>{summary}</p>
                </div>
              ) : (
                <div className="h-full flex items-center justify-center text-gray-400">
                  <p className="text-center">
                    Your summary will appear here<br />
                    <span className="text-sm">Write content and click "Create Summary"</span>
                  </p>
                </div>
              )}
            </div>
            
            {summary && (
              <div className="flex justify-end mt-4">
                <Button
                  onClick={() => {
                    toast({
                      title: "Summary copied!",
                      description: "The summary has been copied to your clipboard.",
                    });
                  }}
                  variant="outline"
                >
                  Copy Summary
                </Button>
              </div>
            )}
          </div>
        </div>
      </div>
    </MainLayout>
  );
};

export default Workspace;
